use dune.com queries instead of snails GraphQL API to avoid blocks

diff --git a/.github/workflows/collect.yaml b/.github/workflows/collect.yaml
--- a/.github/workflows/collect.yaml
+++ b/.github/workflows/collect.yaml
@@ -30,22 +30,27 @@ jobs:
 
       - name: get population
         id: check_pop
-        continue-on-error: true
         run: |
-          python main_pop.py --binary-log -o data/pop.bin
+          python main_pop_dune.py --binary-log -o data/pop.bin
 
-      - name: handle API 403 fail
-        if: steps.check_pop.outcome == 'failure'
-        run: |
-          A=$(cat data/fail.pop.dat || echo 0)
-          B=$(expr $A \+ 1)
-          echo $B fails in a row
-          echo $B > data/fail.pop.dat
+      # - name: get population
+      #   id: check_pop
+      #   continue-on-error: true
+      #   run: |
+      #     python main_pop.py --binary-log -o data/pop.bin
 
-      - name: handle API 403 pass
-        if: steps.check_pop.outcome == 'success'
-        run: |
-          echo 0 > data/fail.pop.dat
+      # - name: handle API 403 fail
+      #   if: steps.check_pop.outcome == 'failure'
+      #   run: |
+      #     A=$(cat data/fail.pop.dat || echo 0)
+      #     B=$(expr $A \+ 1)
+      #     echo $B fails in a row
+      #     echo $B > data/fail.pop.dat
+
+      # - name: handle API 403 pass
+      #   if: steps.check_pop.outcome == 'success'
+      #   run: |
+      #     echo 0 > data/fail.pop.dat
 
       # - name: get burn coefficient
       #  run: |
